package com.example.accessingdatarest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;


@Controller // This means that this class is a Controller
@RequestMapping(path = "/example") // This means URL's start with /demo (after Application path)
public class MyController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private PersonRepository personRepository;

	

	@GetMapping(path = "/1")
	public @ResponseBody Iterable<Person> getAllUsers() {
		
		Person n = new Person("jon", "doe");

		personRepository.save(n);
		// This returns a JSON or XML with the users
		return personRepository.findAll();
	}
}


